AWSTemplateFormatVersion: 2010-09-09
Description: This is my gitsync demo template

Resources:
  GitsyncVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
      - Key: Name
        Value: gitsyncvpc-divas

  GitsyncSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GitsyncVpc
      CidrBlock: 10.0.0.0/24
      Tags:
      - Key: Name
        Value: gitsyncsubnet2
